language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"

deploy:
  provider: s3
  access_key_id:
    secure: "AKIARBDC6E6PC6ZKHQ54"
  secret_access_key:
    secure: "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"
  bucket: "ecommerce-nodes"
  edge: true
  on:
    branch: master
    

after_deploy: 
  - ./run.sh