language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"

install:
  - cd npm install && cd ..

deploy:
  provider: s3
  access_key_id:
    secure: "AKIAICLDSQ5BER64XTBA"
  secret_access_key:
    secure: "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"
  bucket: "ecommerce-trial"
  edge: true
  on:
    branch: staging
    

after_deploy: 
  - ./run.sh