language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"

deploy:
  provider: elasticbeanstalk
  access_key_id: "$ACCESSKEYID"
  secret_access_key: "$SECRETACCESSKEY"
  region: "us-east-1"
  app: "node-ecco"
  env: "node-ecc0-environment"
  bucket_name: "node-echo"
  on:
    branch: elasticbean
    

after_deploy: 
  - ./run.sh