language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"

deploy:
  provider: s3
  access_key_id:
    secure: "${ACCESSKEYIDZ}"
  secret_access_key:
    secure: "${SECRETACCESSKEY}"
  bucket: "ecommerce-trial"
  edge: true
  on:
    branch: staging
    

after_deploy: 
  - ./run.sh