language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: AKIARBDC6E6PLIMPM3OA
  secret_access_key:
    secure: "${SECRETACCESSKEY}"
  region: "us-east-1"
  app: "ecommerce"
  env: "production"
  bucket: "ecommerce-nodes"
  on:
    branch: master

  after_deploy: 
  - ./run.sh