language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"

deploy:
  provider: s3
  access_key_id:
    secure: "AKIARBDC6E6PC6ZKHQ54"
  secret_access_key:
    secure: "${SECRETACCESSKEYZ}"
  region: "us-east-1"
  app: "ecommerce"
  env: "production"
  bucket: "ecommerce-nodes"
  edge: true
  on:
    branch: master
    

after_deploy: 
  - ./run.sh