language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"

deploy:
  provider: codedeploy
  access_key_id: "AKIARBDC6E6PLIMPM3OA"
  secret_access_key: "${SECRETACCESSKEY}"
  bucket: "ecommerce-nodes"
  key: latest/MyApp.zip
  bundle_type: zip
  application: MyApp
  deployment_group: MyDeploymentGroup
  on:
    branch: master

  after_deploy: 
  - ./run.sh