language: node_js
node_js: 
  - "stable"

deploy:
  provider: elasticbeanstalk
  access_key_id: "$ACCESSKEYID"
  secret_access_key: "$SECRETACCESSKEY"
  region: "us-east-2"
  app: "nodeecco"
  env: "Nodeecco-env"
  bucket_name: "elasticbeanstalk-us-east-2-173333581312"
  on:
    branch: elasticbean
    

after_deploy: 
  - ./run.sh