language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"

deploy:
  provider: s3
  access_key_id:
    secure: "${AKIARBDC6E6PC6ZKHQ54}"
  secret_access_key:
    secure: "${SECRETACCESSKEYZ}"
  bucket: "ecommerce-nodes"
  edge: true
  on:
    branch: staging
    

after_deploy: 
  - ./run.sh