language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"

deploy:
  provider: s3
  access_key_id: "$ACCESSKEYID"
  secret_access_key: "$SECRETACCESSKEY"
  bucket: "ecommerce-trial"
  edge: true
  on:
    branch: staging
    

after_deploy: 
  - ./run.sh